# Generated by Django 2.1.7 on 2019-03-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='name',
            new_name='nome',
        ),
    ]
